models:
  # DDPM模型
  ddpm:
    image_unet:
      model_class: "TrafficUNet"
      parameters:
        num_classes: 1
        time_embed_dim: 128
        class_embed_dim: 128
        condition_fuse_dim: 128
        conv_in_channels: 3
        down_channels: [64, 128, 256, 512]
        
    table_ddpm:
      model_class: "ConditionalDDPM"
      parameters:
        feat_dim: "auto" 
        t_dim: 64
        hidden_dims: [128, 128]
        residual_blocks: 2

  # 多模态模型
  multimodal:
    teacher:
      model_class: "MultiModalIDS"
      parameters:
        num_classes: "auto"
        feature_dim: "auto"
        image_branch_channels: [16, 32, 64, 128]
        feature_branch_dims: [128, 64]
        classifier_dims: [128, 64]
        dropout: 0.5
        
    student:
      model_class: "DistilledStudentModel"
      parameters:
        num_classes: "auto"
        feature_dim: "auto"
        image_size: 32
        image_branch_channels: [8, 16]
        feature_branch_dims: [32]
        classifier_dims: [64]

  # 基准模型
  baselines:
    mobilenetv3:
      model_class: "models.mobilenet_v3_large"
      pretrained: true
      input_size: 224
      
    shufflenet:
      model_class: "models.shufflenet_v2_x1_0"
      pretrained: true
      input_size: 224
      
    alexnet:
      model_class: "models.alexnet"
      pretrained: true
      input_size: 224
      
    efficientnet_lite:
      model_class: "EfficientNet.from_pretrained"
      pretrained_name: "efficientnet-b0"
      input_size: 224
      
    resnet50:
      model_class: "models.resnet50"
      pretrained: true
      input_size: 224